### PR TITLE
Login rework

### LINKED ISSUE #12: Login fails after session timeout
Trying to login again after the session timed-out will cause client to die, since session deletion attempt will fail (we have no valid auth token at that moment and session might already be deleted).

To fix this, we need to re-thing the session login/logout logic to account for the facts above.

### PR DESCRIPTION
**Pull request by tadeboro**
This pull request introduces semi-automatic login session renewal. Unfortunately, we were forced to change quite a bit of code since login functionality was moved one abstraction layer down in the library: from the resource level to connector level.

Fixes #12

### CODE REVIEW

File: lib/redfish_client/connector.rb [hunk 1]
```diff
@@ -52,10 +68,18 @@ def remove_headers(headers)
...
+    #
     # @param path [String] path to the resource, relative to the base url
     # @return [Excon::Response] response object
     def get(path)
-      @connection.get(path: path, headers: @headers)
+      return @cache[path] if @cache[path]
+
+      @connection.get(path: path, headers: @headers).tap do |r|
+        @cache[path] = r if r.status == 200
+      end
```
[the remark this answers is not in the document]
Comment (tadeboro) [reply lib/redfish_client/connector.rb]: Above three lines are equivalent to:

    r = @connection.get(path: path, headers: @headers)
    if r.status == 200
      @cache[path] = r
    end
    r

`tap` always returns `self`, block is used for side-effects only, which makes it really useful in situations such as above, where we can remove the temporary variable and unclutter the code.

File: lib/redfish_client/resource.rb [hunk 2]
```diff
@@ -103,13 +103,6 @@ def respond_to_missing?(symbol, include_private = false)
       key?(symbol.to_s) || super
     end
 
-    # Clear the cached sub-resources.
-    #
-    # This method is a no-op if connector in use does not support caching.
-    def reset
-      @connector.reset if @connector.respond_to?(:reset)
-    end
-
```
Comment (matejart) [inline lib/redfish_client/resource.rb]: Lines 18-21 talk about the `reset` method, Is that still relevant?

Comment (matejart) [reply lib/redfish_client/resource.rb]: If you remove these methods, is there any other way to manage cache? From what I've seen, the functionality is now only in the connector, which is not exposed to the developers. What is the approach for requesting a cache invalidation and getting a new value from the server?

File: lib/redfish_client/connector.rb [hunk 3]
```diff
@@ -73,11 +79,11 @@ def remove_headers(headers)
     # remote and then cached, but only if the response has an OK (200) status.
     #
     # @param path [String] path to the resource, relative to the base url
-    # @return [Excon::Response] response object
+    # @return [Response] response object
```
Comment (matejart) [inline lib/redfish_client/connector.rb]: Would it make sense to use `Connector::Response` here as well to be consistent with the documentaiton elsewhere? Or is it a convention to omit what is actually the defining class?

File: spec/redfish_client/resource_spec.rb [hunk 4]
```diff
@@ -269,7 +269,7 @@
 
   context "#delete" do
     it "returns response instance" do
-      expect(resource.delete).to be_a Excon::Response
+      expect(resource.delete).to be_a RedfishClient::Connector::Response
```
Comment (matejart) [inline spec/redfish_client/resource_spec.rb]: Nitpicking: you added parentheses `()` in the other test cases, but not here. In an earlier commit you removed them elsewhere.
In my opinion it is fine without them.

File: spec/redfish_client_spec.rb [hunk 5]
```diff
@@ -5,63 +5,43 @@
...
+      expect(described_class.new("http://example.com", prefix: "/custom").c)
+        .to eq("d")
     end
 
     it "creates caching connector by default" do
-      client = described_class.new("http://example.com")
-      expect(client.sub.key).to eq("custom_val")
+      stub_request(:get, "http://example.com/redfish/v1")
+        .to_return(status: 200, body: '{"e": "f"}')
+        .to_raise("Should not be here")
```
Comment (matejart) [inline spec/redfish_client_spec.rb]: I really like this solution 👍

File: lib/redfish_client/connector.rb [hunk 6]
```diff
@@ -126,10 +133,57 @@ def reset(path = nil)
...
+    def set_auth_info(username, password, auth_test_path, session_path = nil)
+      @username = username
+      @password = password
+      @auth_test_path = auth_test_path
+      @session_path = session_path
+    end
+
+    # Authenticate against the service.
+    #
+    # Calling this method will try to uthenticate against API using
```
Comment (matejart) [inline lib/redfish_client/connector.rb]: **a**uthenticate

File: lib/redfish_client/resource.rb (hunk 2 above)
Comment (tadeboro) [reply lib/redfish_client/resource.rb]: I was wondering why this was not as obvious as I thought it was. And then I found out that I did not create a separate commit that introduced this functionality. So I did what I should have done when initially committing changes: split this into separate commit. Thanks for spotting this.

File: lib/redfish_client/connector.rb (hunk 3 above)
Comment (tadeboro) [reply lib/redfish_client/connector.rb]: Documentation generator will this resolve properly, so there is no need to prefix the type with parent module/class.

File: spec/redfish_client/resource_spec.rb (hunk 4 above)
Comment (tadeboro) [reply spec/redfish_client/resource_spec.rb]: It seems I missed that one. Usually, the only method call that I leave without parentheses is `.to`. This adds a nice visual separation of test and expected result. Since this test was changed later on, I will leave this as is.

File: spec/redfish_client/connector_spec.rb [hunk 7]
```diff
@@ -178,4 +190,106 @@
...
+  context "#logout" do
+    it "removes basic auth info from requests" do
+      stub_request(:get, "http://auth.demo/test")
+        .with(basic_auth: %w[user pass])
+
+      connector = described_class.new("http://auth.demo")
+      connector.set_auth_info("user", "pass", "/test")
+      connector.login
+
+      connector.logout
```
[the remark this answers is not in the document]
Comment (tadeboro) [reply spec/redfish_client/connector_spec.rb]: I was also thinking about this when I wrote this test. Ultimately I decided to skip this since testing re-authentication and other stuff is really not the purpose of this test (we already do this elsewhere). This test asserts that if we need to invalidate credentials when using basic authentication, no API calls are made and things do not blow up.

Anything else would be better suited for integration testing.

File: spec/redfish_client/connector_spec.rb [hunk 8]
```diff
@@ -178,4 +190,106 @@
...
+          status: 201,
+        )
+      stub_request(:delete, "http://auth.demo/sessions/456")
+        .to_return(status: 204)
+
+      connector = described_class.new("http://auth.demo")
+      connector.set_auth_info("user", "pass", "/test", "/sessions")
+      connector.login
+
+      connector.logout
```
[the remark this answers is not in the document]
Comment (tadeboro) [reply spec/redfish_client/connector_spec.rb]: Not sure why I wrote test without asserts on deletes, since this is the main thing we are testing. I will add an assert statement at the end of the test.

File: spec/redfish_client/root_spec.rb [hunk 9]
```diff
@@ -6,6 +6,41 @@
...
+      expect(connector).to receive(:set_auth_info).with(
+        "u", "p", "/t", "/s"
+      )
+      expect(connector).to receive(:login)
+
+      raw = {
+        "a" => { "@odata.id" => "/t" },
+        "Links" => { "Sessions" => { "@odata.id" => "/s" } },
+      }
+      described_class.new(connector, raw: raw).login("u", "p")
```
[the remark this answers is not in the document]
Comment (tadeboro) [reply spec/redfish_client/root_spec.rb]: Again, this is just me being silly and not adding any asserts.

**Comment by tadeboro** [comment]
Thanks for the comments @matejart. I fixed all the stings that I messed up and things should be in better shape now. Main things I did:

 1. split last commit into three separate commints with clearly stated intentions,
 2. fix the useless logout tests,
 3. touch up the spelling  in comments and
 4. update library documentation (remove references to methods that do not exist anymore).
